name: Build and Publish

on:
  # This workflow is triggered when a commit is pushed to `master`. This is
  # typically when a PR is merged, since no one is pushing commits directly to master
  push:
    branches:
      - master
  # This workflow is also triggered when a PR is opened, updated, or a label is applied
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  generate_version:
    name: Generate version
    runs-on: [self-hosted,zendesk-stable]
    outputs:
      library_base_version: ${{ steps.fetch_and_generate.outputs.library_base_version }}
    env:
      GITHUB_RUN_NUMBER: ${{ github.run_number }}
    steps:
      - uses: zendesk/checkout@v2
        with: # Check out the branch from our PR
          ref: ${{ github.head_ref }}
      - name: Fetch and generate
        id: fetch_and_generate
        shell: bash
        run: |
          GRADLE_VERSION=$(grep -o "^version=.*" gradle.properties | grep -Eo "[0-9]+\.[0-9]+")
          BRANCH_NAME=$(echo "${GITHUB_HEAD_REF:-$GITHUB_REF}" | sed -e 's/refs\/heads\///')
          SHORT_SHA=$(git rev-parse HEAD | head -c 10)

          if [ "$BRANCH_NAME" != "master" ]; then
            SANITIZED_BRANCH="$(echo $BRANCH_NAME | sed -e 's/\//_/g')_"
          else
            SANITIZED_BRANCH=""
          fi

          VERSION=$GRADLE_VERSION.$GITHUB_RUN_NUMBER.$SANITIZED_BRANCH$SHORT_SHA
          echo "::set-output name=library_base_version::$VERSION"
  create_release:
    name: Create release
    runs-on: [self-hosted,zendesk-stable]
#    if: (github.event.push != null)
    needs:
      - generate_version
    steps:
      - "env":
          "GITHUB_TOKEN": "${{ github.token }}"
          "LIBRARY_BASE_VERSION": ${{ needs.generate_version.outputs.library_base_version }}
          "JAVA8_VERSION": ${{ needs.build_java_8.outputs.version }}
          "JAVA17_VERSION": ${{ needs.build_java_17.outputs.version }}
        "id": "create_release"
        "name": "Create release"
        "uses": "zendesk/create-release@v1.1.1"
        "with":
          "body": |
            This release includes generated configuration artifacts that are dependent on a successful Docker build for both Java 8 and Java 17.


          "commitish": "${{ github.sha }}"
          "release_name": "${{ env.LIBRARY_BASE_VERSION }}"
          "tag_name": "${{ env.LIBRARY_BASE_VERSION }}"
